### ISSUE TITLE
serve-web asks the browser to cache files  breaking livereload

### ISSUE THREAD

**Issue by sciabarracom** [nimbella/nimbella-cli#110]
If you try to inspect headers of any file served by `serve-web` you get this

```
< cache-control: max-age=3600
```

This instructs the browser to cache files for one hour.
I
Unfortunately this breaks any `livereload` you may want to use with `web-serve`.

**Comment by rabbah** [comment]
The cache should be disabled for local dev.

**Comment by sciabarracom** [comment]
Fixed in PR#114
