### ISSUE TITLE
nim auth logout for namespace on multiple hosts

### ISSUE THREAD

**Issue by rabbah** [nimbella/nimbella-cli#127]
```
> nim auth logout abc-
0: abcdef on https://host1
1: abcdef on https://host2
Choose by number: 1
 ›   Error: The namespace 'abcdef' exists on more than one API host.  An '--apihost' argument is required
```

The choice does not matter - tried with both 0 and 1.

**Comment by rabbah** [comment]
This works as expected, but specifying the complete namespace results in an error - which already exists so could be a separate issue:

```
./bin/run auth logout abcdef
 ›   Error: The namespace 'abcdef' exists on more than one API host.  An '--apihost' argument is required
```

but 

```
./bin/run auth logout abcdef-
```

will show the selection menu and work as desired. Is this a feature or a bug?

**Comment by bhageena** [comment]
This has been a deliberate behavior, and we intentionally kept it intact in recent changes, https://github.com/nimbella/nimbella-cli/issues/52#issuecomment-791369052

**Comment by rabbah** [comment]
For the linked comment “ I think we all agree that a trailing hyphen should not be required when the full namespace name has been typed and we are simply triggering the new feature, which is to prompt if that namespace exists on multiple API hosts.”

As such we aren’t automatically doing anything simply allowing the user the convenience of selecting a host. I don’t think the behavior for when to show the prompt should vary based on the presence of the -  (if the host is ambiguous, show the prompt).

**Comment by rabbah** [comment]
It’s fine to merge the pr and continue discussion.
