### ISSUE TITLE
confusing cli error when builder is not available 

### ISSUE THREAD

**Issue by rabbah** [nimbella/nimbella-cli#138]
This has to be replicated on a deployment not enabled for remote builds.
```
> nim project deploy hello --remote-build

Failures:
 ›   Error: While deploying action 'hello/swift5.4': the requested resource does not exist. (404 Not Found)
```

But if you enable debug logs with `DEBUG=*` you'll see the 404 is actually from the missing builder API for this runtime.

**Comment by jthomas** [comment]
Should be fixed with: https://github.com/nimbella/nimbella-deployer/releases/tag/v2.1.1
