### ISSUE TITLE
Developer errors in remote builds come back as timeouts

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [nimbella/nimbella-cli#163]
In developing some non-trivial Swift code that needs to be built remotely, I have discovered that any error in that code will cause the builder action to time out.  There is little useful information in the activation record to explain the real cause.

This turns out to be due a bug in the code body for those builder actions that are not for node runtimes (e.g. the code body that is used for Swift, Java, Python, Php, Go, etc).    When the action was adapted to run `nim` in the runtime container, logic was added to look for a non-zero exit code from `nim` and follow a generic "error" path in that case.   This was a mistake because `nim project deploy` returns both successes and errors using the same structure and merely sets the non-zero exit code in the error case. 

The fix is to remove the clause that responds to a non-zero exit code from `nim` and instead
- if `nim` returns without barfing (it is designed to do so), just follow the same path for both successes and failures.  True, this will result in the action execution being labelled a "success" but I would argue that it is a success (it successfully ran the build and returned the result, despite the developer perhaps being unhappy with said result).   The `nim` command that is driving the remote build knows how to interpret error returns and will do the right thing (down to displaying the stack trace when `--verbose` is specified).
- if `nim` barfs (or anything in the Python logic of the action barfs), then the original error return is activated.  This appears to work correctly.   In this proposed change, this would generally indicate system errors rather than developer ones, but could still be triggered by developer errors in areas where `nim` error handling is flawed.

I do _not_ know exactly why the action hung when attempting to follow the flawed error logic.  But, as the logic was flawed, it can safely be removed.

I can't submit a PR to fix this because the code to the builder actions is sourced in a repo to which I do not have access.   However, I can read the code because the builder actions are public.   Here is a patch:
```diff
--- build_swift_5.4.swift	2021-08-17 14:45:06.000000000 -0400
+++ builder/packages/builder/build_swift_5.4.swift	2021-08-17 14:47:52.000000000 -0400
@@ -34,14 +34,11 @@
     print(cmd)
     p = subprocess.Popen(cmd, stdout=subprocess.PIPE,
            stderr=subprocess.PIPE, env=env)
+    print("subprocess created")
     (o, e) = p.communicate()
+    print("subprocess finished, rc=%d" %(p.returncode))
     if o and isinstance(o, bytes) and not isinstance(o, str):
         o = o.decode('utf-8')
-    if not p.returncode == 0:
-        if e and isinstance(e, bytes) and not isinstance(e, str):
-            e = e.decode('utf-8')
-        errReturn = "%s%s" % (o, e)
-        return json.dumps({ "error": errReturn })
     return o
 
 def main(env, args):
```

**Comment by jthomas** [comment]
@joshuaauerbachwatson this is wonderful! I have definitely seen this behaviour with the Swift runtime (timing out randomly on builds) and hadn't got round to investigating. I'm glad you actually got to the root cause of this. Let me have a look into importing this code - will let you know.

**Comment by joshuaauerbachwatson** [comment]
Yes @jthomas please let me know when this is fixed in the builder actions and the replacement actions are installed on `nimgcp` and `eksitaly`.

In addition to the problem whose remedy I described above (which affects the action code used for all non-nodejs runtimes) there are also some problems specific to the Swift runtime.   These cannot be fixed in the build action but require changes to some scripts included in that runtime itself.  The Nimbella forks of Apache runtime code are public but do not appear to accept issues or PRs.  In addition, I would have trouble testing changes to a runtime.   Shall I follow the same procedure as in the above (post changes to this issue for you to follow up on)?    Specifically:

1.   The `/bin/compile` script in the Swift runtime does not propagate a non-zero exit code when the Swift build it is running fails.   That makes it hard to observe errors because the standard `nim` behavior is to only display build output on failure, where failure is defined as a non-zero exit code.   This is related to issue nimbella/deployer#19 but needs to be fixed in addition.
2.  The provided `defaultBuild` script (this is something Nimbella added, not present upstream), is flawed because it runs some builds directly in the `/swiftAction` directory, which produces non-idempotent behavior.   As a result, package manager (multiple files with dependencies) builds cannot be run twice in the same container.   That is
- All Swift builds run fine in cold containers
- Single-file Swift builds also run fine in warm containers
- Package manager builds run fine in warm containers as long as all previous builds in the container were single-file
- Package manager builds fail in warm containers when a previous package manager build was run in that container

I am experimenting with the correct fix to `defaultBuild`.

**Comment by joshuaauerbachwatson** [comment]
As noted in nimbella/nimbella-sdk-swift#1, my earlier proposed fix to the builder action now appears to be present on `eksitaly` but not on `nimgcp`.   No matter, because, as is  noted later in that issue, there are remaining problems with the action, including remaining cases where errors cause it to time out.   The cases that are still problematic are those in which `nim` does not return anything in stdout because it has failed to handle an exception, which leaks and appears only on stderr.   And, in all cases where the code ended up synthesizing a response from error information it was neglecting the final newline (that's what actually causes the timeouts).

I've done a more extensive rewrite of the action fixing (I hope) all of the remaining problems with the error paths and I now propose the following.    The diff is against the original version of the action still present on `nimgcp` (that is, it is in lieu of, rather than on top of, my original proposal).   The new version has been "tested" in the sense that it is what I am actively using for Swift builds, and I do a lot of them, including many that have errors. 

```
--- build_swift_5.4.swift	2021-09-05 14:18:28.000000000 -0400
+++ builder/packages/builder/build_swift_5.4.swift	2021-09-05 14:27:21.000000000 -0400
@@ -34,14 +34,27 @@
     print(cmd)
     p = subprocess.Popen(cmd, stdout=subprocess.PIPE,
            stderr=subprocess.PIPE, env=env)
+    print("subprocess created")
     (o, e) = p.communicate()
-    if o and isinstance(o, bytes) and not isinstance(o, str):
-        o = o.decode('utf-8')
-    if not p.returncode == 0:
-        if e and isinstance(e, bytes) and not isinstance(e, str):
-            e = e.decode('utf-8')
-        errReturn = "%s%s" % (o, e)
-        return json.dumps({ "error": errReturn })
+    print("subprocess finished, rc=%d" %(p.returncode))
+    if o:
+        if isinstance(o, bytes) and not isinstance(o, str):
+            print("decoding stdout")
+            o = o.decode('utf-8')
+        else:
+            print("not decoding stdout")
+    else:
+        print("stdout is empty")
+        if e:
+            if isinstance(e, bytes) and not isinstance(e, str):
+                print("decoding stderr")
+                e = e.decode('utf-8')
+            print("contents of stderr:")
+            print(ascii(e))
+            o = json.dumps({ "error": "remote nim terminated unexpectedly with error: see activation record for details"}) + "\n"
+        else:
+            print("stderr is empty")
+            o = json.dumps({ "error": "remote nim terminated with unexplained error"}) + "\n"
     return o
 
 def main(env, args):
@@ -49,7 +62,9 @@
     env["OW_COMPILER"] = "/bin/compile"
     env["HOME"] = "/"
     env["WORKDIR"] = os.getcwd()
+    print("calling build")
     res = build(env, args)
+    print("build returned")
     return res
 
 if __name__ == "__main__":
@@ -73,8 +88,9 @@
         try:
             res = main(env, payload)
         except Exception as ex:
+            print("exception in main")
             print(traceback.format_exc(), file=stderr)
-            res = json.dumps({ "error": ex.__doc__ })
+            res = json.dumps({ "error": "exception in main: see activation record for details"}) + "\n"
         out.write(res.encode('utf-8'))
         stdout.flush()
         stderr.flush()
```

**Comment by joshuaauerbachwatson** [comment]
> The cases that are still problematic are those in which `nim` does not return anything in stdout because it has failed to handle an exception, which leaks and appears only on stderr.

As noted in the Swift SDK issue, these cases actually arise not (usually) because of leaked exceptions but because `nim` is deliberately printing an error to stderr and terminating.    This means that my proposal of the previous comment needs further revision.   It is not correct to treat these as "system errors" and refer the developer to the activation logs, because these are actually (in some cases) routine developer errors that should be fed back in a way consistent with how all such errors are reported.   So, expect a further revision of the action code.

**Comment by joshuaauerbachwatson** [comment]
> So, expect a further revision of the action code.

The revision is now being hosted in a public repo: https://github.com/joshuaauerbachwatson/remoteBuildAction.

As mentioned earlier, I lack the means to turn this into a PR.

**Comment by jthomas** [comment]
Josh - thanks for this, it looks good. Let me review and work on getting it merged.

**Comment by joshuaauerbachwatson** [comment]
I'm leaving this open not because I think there's more work to do for me but because the change has not been fully rolled out by Nimbella.

**Comment by joshuaauerbachwatson** [comment]
It appears the change will not be rolled out to apigcp but will appear in a future deployment.  Since coding and testing is complete, closing this.
