### ISSUE TITLE
NPM publishing fails - `postpack` script not working.

### ISSUE THREAD

**Issue by jthomas** [nimbella/nimbella-cli#171]
In the `npm publish` output - I see this error:

```
cp: nimbella-nimbella-cli-*.tgz: No such file or directory
```

The `postpack` script is executed - which tries to do `cp nimbella-nimbella-cli-*.tgz nimbella-cli.tgz`, but the packed tgz is not created in the CWD during the publish command. This is a feature/bug of NPM: https://npm.community/t/can-we-access-tarball-in-postpack-while-doing-npm-publish/6956

Since we don't really need this command to happen during publish - I'll revert the change.

**Comment by bhageena** [comment]
` cp nimbella-nimbella-cli-*.tgz nimbella-cli.tgz` was to ensure that we have minimal changes in other places, since moving to npm means changed tar filename
looking into alternatives

**Comment by bhageena** [comment]
There doesn't seem to be an easy way out https://npm.community/t/postpack-hook-has-no-access-to-the-generated-tgz-for-inspection/9025.
Will raise a PR for workbench build script.
