### ISSUE TITLE
Improvements to project create

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [nimbella/nimbella-cli#185]
This is intended to be a small focused issue, not to be confused with the more ambitious #29.

1.  A created project should always create a folder for each action.   This makes the project structure a bit more complex-seeming but it pays off when the developer then wants to use the created project as the starting point for something more ambitious. 
2.  The package should be something like `sample` rather than `default` because the default package isn't "real" and not all `package.yml` features work on it.  The developer should be able to exercise all the features early on.  Of course, the package can always be renamed by the developer.
3.  There should be a `.gitignore` at least sufficient to prevent the generated `.nimbella` folder from being accidentally committed.    We can consider what else should be added to it (suggestions welcome).
4.  (More arguable, may have a good reason to hold off on it).   A `project.yml` should be added by default and not require an extra flag.

**Comment by joshuaauerbachwatson** [comment]
The following problem was reported recently:

The project:create help output implies "PROJECT" is optional, but it doesn't handle that correctly

*Actual result:*
```
$ nim project create --help 
...
nim project:create [PROJECT]
...

$ nim project create  --type=sample
A sample project called 'sample' was created for you.
You may deploy it by running the command shown on the next line:
  nim project deploy sample
```

*Expected result:*
- the output should show that PROJECT is a required value
- the creation should validate that PROJECT was not passed

I believe the code is behaving as intended but I don't blame the reporter for expecting otherwise.  The design is confusing, and should be revised in the scope of this issue.  

The current intent:
- project is optional, in general
- when both project and type are omitted, help is displayed (implying that one or the other is required, although there is no error message)
- when project is omitted and type is `postman` or `openapi`, the project name is taken from the specification
- when the project is generated and type is `sample` a default project name of `sample` is used

What makes this even more confusing is the limitation of the `oclif` parsing template and usage generator, which doesn't know how to express a situation as complex as the previous so it just lists the project as optional.

The motivation for this complexity are the needs associated with the `postman` and `openapi` plugins, where the project _should_ be named in concert with the spec to permit keeping the two synchronized.

I am currently not sure how aggressively these plugins will be supported so, I list two possible dispositions.

1.  Simply make `project` a required operand, simplify `project create` and discontinue support for the plugins.
2. Continue support for the plugins but handle the complexity more gracefully
    - project is indeed "optional" but
    - it can only be omitted if the project is being generated from a specification, otherwise it's an error
    - if it's provided and the specification provides a name and the two conflict, that should be an error also
    - some indication of this reality should be customized into the usage diagram, if possible

**Comment by rabbah** [comment]
> it can only be omitted if the project is being generated from a specification, otherwise it's an error

i prefer this path; or can we make the project name always required and reject a project name that doesn’t match a specification when using the postman rested plugins? (Would that simplify the command usage?)

**Comment by rabbah** [comment]
I favor “ if it's provided and the specification provides a name and the two conflict, that should be an error”, while making the project name always required (not clear to me if that was the case with this proposal). 

That is always required (and we continue to support the plugin).

**Comment by joshuaauerbachwatson** [comment]
> That is always required (and we continue to support the plugin).

Not exactly what i meant but having thought about it I now _mostly_ agree.   There is a subtlety.

I agree that the usage help should show the argument as required since it is always accepted and sometimes required and the cases where it is required are the cases you are likely to try first.

But, I was concerned that, in the case where the user is importing from a spec, since we think it is important for the project name to match the spec and will throw an error if it doesn't, the user is going to just see it as annoying that he has to specify information explicitly on the command line that can be obtained from the spec he is importing.   Why not shortcut this for convenience?

However, this does not need to be done by making the argument optional in some cases but not others.   Instead, we could accept a special token like `-` or `--` (not `*` please, I hate fighting with the shell).   This would mean "use the name from the spec" and would be illegal in the cases where there is no spec.

**Comment by joshuaauerbachwatson** [comment]
The first thing I want to do here is to simplify the code in project create somewhat.  It has gotten a bit confused due to the dual purposes of supporting the spec-importing plugins and also simple sample projects.   One way it could be simplified would be to stop keeping the plugins at arms length but simply assume they are present.   Also, since we never completely got the dispatch table for project types to be completely dynamic (there is always a static enumeration somewhere) we could consider having them be not formal `oclif` plugins but incorporated in some other way.   This might mean physical incorporation into the code base or it might mean a simple static dependency in `package.json`.   Before committing to any of these changes, though, I need to try out some alternatives to see what effect they have on the overall bulk of the CLI.

**Comment by joshuaauerbachwatson** [comment]
I note that the "fat tarball size" (including `node_modules` but excluding `node`) is about 13 meg now.

I did the experiment to remove the "plugins plugin" and declare static dependencies on `postman-plugin` and `postman-openapi`.    The fat tarball size ballooned to 57 meg.   In addition there are now 60 vulnerabilities, 25 of them high severity and only 4 of them low.

At the same time, I investigated the mechanism by which we manage the parsing for `nim project create` with different "type" values.   Discoveries:

1.  (as mentioned before) the supported plugins must be statically enumerated anyway.
2. The logic to incorporate different flag options for different types works when executing but does not show up in any usage.   The only way to see a usage diagram for postman or openapi import is to execute the undocumented hidden command that the plugin uses to attach to the command tree.

Having thought about the current state of affairs and the various iterations we have gone through to try to get to a single unified `project create` command, I am concluding that that is a fundamentally problematic design.   We would be better off radically simplifying `project create` (as the on-ramp for naive new users) and having a separate `project import` command to contain the more advanced cases.   Many flags. are (and probably would be) in common when importing but irrelevant for the simple "create with sample" case.

Conclusions:

1.  I am not statically incorporating these plugins at this time.   We would need to at least remove vulnerabilities from them and probably more than that: see if we can trim their size to be more tractable.
2.  I will, however, remove the plugins plugin and disable the support for the "advanced" create options.   This is a breaking change but it is likely that the changes to `project create` behavior already contemplated are already breaking and we will need a new major version anyway.   Recall that users of `nimbella.io` will not be affected as long as they continue to use the last supported version there downloaded from `nimbella.io`.
3. Because of the way incorporation works, the plugins themselves (which are in a separate repo) are self-contained and able to be easily revived in the future.
4. While the plan of record will be to eventually introduce `project import` to host these plugins (either with static incorporation or dynamic), I am doing nothing about that right now.

**Comment by joshuaauerbachwatson** [comment]
This work is close to complete and is staged in PR #209.  Before merging I want to look at adding permanent tests to the current `bats` suite (I may decide to defer this).  I did manually test all the languages to see if the sample projects would deploy and run correctly.   There appears to be a problem with `dotnet` which I am investigating.   All the others are fine.

**Comment by joshuaauerbachwatson** [comment]
In adding `bats` testing for `project create` I noted that the test for `typescript` often times out in the invoke phase.    Submitting source code to the typescript runtime works because it has a compile capability, but failure to pre-compile typescript can cause even a trivial program to blow the 3 second limit.   The test is skipped for now.

**Comment by joshuaauerbachwatson** [comment]
When the tests were run automated under circleci upon push, the java example failed also so I added `java` to the list of runtimes for which we bump up the timeout.

**Comment by joshuaauerbachwatson** [comment]
When I do get clean tests on this change and am ready to release it, I do not plan to increase the major version.   The current reality:

- we recently started the 2.x.x series of releases, intended to support future offerings.  This signaled a departure from backward compatibility for `nimbella.io` users
- users of `nimbella.io` are expected to use 1.x.x releases, for which compatibility has been maintained
- the 1.17.0 release will continue to be the official release supported for download from `nimbella.io`
- there will probably be several more breaking changes before things settle down again, at which time we will resume scrupulous adherence to semver principles

tl;dr -- consider 2.x.x releases to be transitional
