### ISSUE TITLE
Feature: add --json flag to nim kv get operation

### ISSUE THREAD

**Issue by rabbah** [nimbella/nimbella-cli#22]
When the kv stores a JSON value, it would be convenient to output it as pretty printed JSON.

```
> nim kv get x
{"a":"A"}
```

```
> nim kv get x --json
{
  "a": "A"
}
```

Even better if it's detected automatically, perhaps.

**Comment by joshuaauerbachwatson** [comment]
@bhageena I assigned this to you ... if you don't have time to work on it, just take your name off and I'll get to it.

The auto-detection idea is worth exploring but AFAIK the only reliable way to test for JSON in a string value is to attempt parsing and catch errors.   That might just work for this case.   If you know a better way, go for it.

**Comment by joshuaauerbachwatson** [comment]
I believe the PR for this has been merged.   I am changing the assignment to myself so I remember to check it off when the next stable version is released.

**Comment by joshuaauerbachwatson** [comment]
In stable version 1.11
