### ISSUE TITLE
alias kv del to kv delete

### ISSUE THREAD

**Issue by rabbah** [nimbella/nimbella-cli#23]
🙏

**Comment by joshuaauerbachwatson** [comment]
@bhageena Hoping you can knock this one off.   If you are under the gun for other things, you can just give it back.  Should be quick though.

**Comment by joshuaauerbachwatson** [comment]
The PR for this has been merged.  I'm changing the assignment to myself to remind me to check it off at the next stable version.

**Comment by joshuaauerbachwatson** [comment]
In stable version 1.11
