### ISSUE TITLE
change nim object list to emit nothing when there are no objects

### ISSUE THREAD

**Issue by rabbah** [nimbella/nimbella-cli#39]
nim object list on an empty bucket prints 'No object available ' for an empty bucket. Note the extra space. This is because there is a prefix that's optionally emitted when specified.

other list operations print '' for the empty list and I propose this command should be consistent (and emit nothing).

**Comment by joshuaauerbachwatson** [comment]
This was addressed as part of PR #55 and is now awaiting a stable version.

**Comment by joshuaauerbachwatson** [comment]
In stable version 1.12
