### ISSUE TITLE
PHP runtime crashes when you deploy a zip file for a non-binary action

### ISSUE THREAD

**Issue by akrabat** [nimbella/nimbella-cli#4]
Given a project.yml with:

```yaml
packages:
  - name: todo
    actions:
      - name: list
        binary: false
```

with the `list` action defined as a directory (`packages/todo/list/`) with two files in it:

```
index.php
additional_functions.php
```

and deployed using `nim project deploy .`

Then the action crashes with this log:

```
$ nim activation logs --last
=== activation logs 54f19b7e5a66478db19b7e5a66078d7a list:0.0.1
2020-08-20T10:06:55.579755557Z stderr: 2020/08/20 10:06:55 http: panic serving 10.44.30.3:33744: runtime error: invalid memory address or nil pointer dereference
```

(full log here: https://gist.github.com/akrabat/74e8e396ecb0f5afe70b30722df83a18)

This occurs because the `project.yml` sets the action's `binary` to `false`, but `nim project deploy` correctly determines that a `zip` file is needed.

Ideally `nim project deploy` should either ignore the `binary` flag when it creates a `zip` file for deployment or it should error with a clear message on how to fix.

**Comment by joshuaauerbachwatson** [comment]
A fix for this problem has been applied to the source.  I did not test it directly with the PHP runtime but I was able to observe the symptom in other runtimes and can verify that built zip will cause `binary: true` regardless of what is in `project.yml`.

The fix will be in the next stable version of `nim`.
