### ISSUE TITLE
nim login --apihost requires protocol on the hostname

### ISSUE THREAD

**Issue by rabbah** [nimbella/nimbella-cli#53]
`nim login --apihost example.com` will hang in the terminal whereas
`nim login --apihost https://example.com` will work as expected.

**Comment by joshuaauerbachwatson** [comment]
In a slack dialog with @rabbah I said I thought this was due to the fact that the login command was not calling `parseAPIHost` as most commands do when an `--apihost` is specified.

This turns out to be wrong.   It is calling that utility.  The bug is even stupider than that.

**Comment by joshuaauerbachwatson** [comment]
There is simply a failure to use the returned value `apihost` in the no-token login case.  It is using the original flag value by mistake.

**Comment by joshuaauerbachwatson** [comment]
Fixed.  Awaiting a stable version.

**Comment by joshuaauerbachwatson** [comment]
In stable version 1.12
