### ISSUE TITLE
PHP Nimbella library is unavailable if you uses your own composer packages

### ISSUE THREAD

**Issue by akrabat** [nimbella/nimbella-cli#6]
If you create your own `vendor` directory for your PHP action so that you can include additional 34d party libraries, then you lose access to the `Nimbella\Nimbella` package and so no longer have access to Redis or storage or whatever else it provides.

Ideally, this library should be open sourced so that it is available in packagist.org and so that I can include it in my own `vendor` directory, or the PHP runtime should always make the `Nimbella` component and its dependencies available regardless of whether a `vendor` directory is provided by the user.

**Comment by akrabat** [comment]
Until this is solved, if you need Redis, you can replace `$redis = (new Nimbella())->redis();` with:

```php
$redis = new Predis\Client([
    'scheme' => 'tcp',
    'host' => $_ENV['__NIM_REDIS_IP'],
    'port' => 6379,
    'password' => $_ENV['__NIM_REDIS_PASSWORD'],
]);
```

**Comment by rabbah** [comment]
This package is now published https://packagist.org/packages/nimbella/nimbella.
