### ISSUE TITLE
Auto zipper breaks with broken links

### ISSUE THREAD

**Issue by sciabarracom** [nimbella/nimbella-cli#73]
If in a folder for autozip there is a broken link, deployment breaks.

Unfortunately this is common when using virtualenv for python, as documented.
So it should be lenient for those errors.

Example:

```
cd packages/default/pyaction
docker run -ti -v $PWD:/mnt --entrypoint=/bin/bash openwhisk/actionloop-python-v3.7
cd /mnt
virtualenv virtualenv
```

Now you have in pyaction a perfectly legit virtualenv with symlins that refers to libraries in the runtime, but autozipping breaks because some links are 'broken'... it is true on the host but not on the runtime...

**Comment by joshuaauerbachwatson** [comment]
This sounds like a valid issue but the scenario you report is about how you can end up with broken links using virtualenv (I believe you) and not about what goes wrong at deploy time when broken links are present.   Can you make a simpler example that illustrates what goes wrong in the autozipper (it shouldn't be necessary to use a container for that, right?).

**Comment by sciabarracom** [comment]
Building a python action with a virtualenv
```
mkdir -p test/packages/test
touch test/packages/test/__main__.py
docker run -ti --entrypoint=/bin/bash -v $PWD/test/packages/test:/mnt openwhisk/actionloop-python-v3.7
cd /mnt
virtualenv virtualenv
exit
nim project deploy test
```
Result:
```
Deploying project '/Users/msciab/demo/test'
  to namespace 'githubsc-x98gwr9ujwl'
  on host 'https://apigcp.nimbella.io'
Deployment status recorded in 'test/.nimbella'

Deployed actions ('nim action get <actionName> --url' for URL):
  - test/__main__
Failures:
 ›   Error: While deploying action 'test/virtualenv': ENOENT: no such file or
 ›   directory, stat '/Users/msciab/demo/test/packages/test/virtualenv/lib/pyth
 ›   on3.7/__future__.py'
```

`__future__.py` is an invalid simbolic link (it points to /usr/local/something)

**Comment by rabbah** [comment]
Here's a potentially simpler example:

```
mkdir -p test/packages/test
touch test/packages/test/__main__.py
mkdir test/packages/test/virtualenv
ln -s /bad/path test/packages/test/virtualenv/__future__.py
```

```
> nim project deploy test
 ›   Error: ENOENT: no such file or directory, stat '/Users/rabbah/projects/nimbella/main/t/test/packages/test/virtualenv/__future__.py'
```

**Comment by sciabarracom** [comment]
Yep. The long example is to justify WHY you may want to zip broken links, and it is the case with the documented and required virtualenv you need to support libraries in Python.

**Comment by joshuaauerbachwatson** [comment]
I have the feeling I fixed something in the area of post-build symlinks. before.   The context is (1) we don't support deliberate symlinks as a way of assembling a project (we provide other mechanisms).  So, during the project reading phase, if a project directory contains a symlink it's an error.  Originally, we did the same in the build / autozip phase.  But (2) I think we encountered other problems with tool-generated symlinks and made a change to tolerate them in the builder phase after all.   But (3) I suspect we only considered valid symlinks, not invalid ones.   I need to do a little digging in the history to find the original issue and fix so that this can be fixed in an appropriate way.

**Comment by joshuaauerbachwatson** [comment]
Fixed, awaiting a stable version.

**Comment by joshuaauerbachwatson** [comment]
This work is done and the feature is listed in the (committed) change log for 1.14.   1.14 is not released yet but is slated to be released during a upcoming knowledge transfer session.   With the listing of the change in the log the need to hold this issue open is gone.
