### ISSUE TITLE
web deployment "sometimes" results in a page not found even if an index.html is there

### ISSUE THREAD

**Issue by sciabarracom** [nimbella/nimbella-cli#88]
It happened a few times and it is happening currently: if you access faas wars home page you get a 404

https://nimbots-apigcp.nimbella.io/ returns 404

but the index.html is there

https://nimbots-apigcp.nimbella.io/index.html

I even cleared and redeployed the entire web content

**Comment by sciabarracom** [comment]
Update: the problem appeared to be local to only one zone (europe) and transient.

**Comment by jthomas** [comment]
@sciabarracom Can we close this issue as "working"?

**Comment by sciabarracom** [comment]
Yep...

-- 
  Michele Sciabarra
  ***@***.*** <mailto:michele%40sciabarra.com>



----- Original message -----
