### ISSUE TITLE
Bats tests assume OS X installation - need to make cross-platform

### ISSUE THREAD

**Issue by jthomas** [nimbella/nimbella-cli#89]
Tests use Bats plugins for additional functionality - which are loaded in the `test_setup.bash` file. This file loads the plugins with the following code:

```
load '/usr/local/lib/bats-support/load.bash'
load '/usr/local/lib/bats-assert/load.bash'
load '/usr/local/lib/bats-file/load.bash'
```

This is based on the location of those files on OS X - which will not work on other platforms (like the CI/CD systems). Work out a fix to allow the location to be platform-specific. This discovered by @bhageena during testing.

**Comment by bhageena** [comment]
Both these setups worked

using brew:
```
TEST_BREW_PREFIX="$(brew --prefix)"
load "${TEST_BREW_PREFIX}/lib/bats-support/load.bash"
load "${TEST_BREW_PREFIX}/lib/bats-assert/load.bash"
load "${TEST_BREW_PREFIX}/lib/bats-file/load.bash"
```
using npm:

in package.json
```
"bats-assert": "git+https://github.com/ztombol/bats-assert.git",
"bats-support": "git+https://github.com/ztombol/bats-support.git",
"bats-file": "git+https://github.com/ztombol/bats-file",
```
in test_setup.bash
```
load "../node_modules/bats-support/load.bash"
load "../node_modules/bats-assert/load.bash"
load "../node_modules/bats-file/load.bash"
```

**Comment by joshuaauerbachwatson** [comment]
This is good insight and brings us to being able to support a `brew` installation of `bats` on both OSX and Linux (if I understand correctly).

Do we have any story about how to run these tests on windows?   I don't think `brew` works there.  I'm not saying this is an immediate requirement (windows tends to be a bit of a stepchild) but it is possible to run `nim` on windows and some people might want to develop `nim` code changes on windows.   Yes, I didn't think of this before and not a reason not to forge ahead.

**Comment by jthomas** [comment]
> This is good insight and brings us to being able to support a `brew` installation of `bats` on both OSX and Linux (if I
> Do we have any story about how to run these tests on windows? I don't think `brew` works there. I'm not saying this is an immediate requirement (windows tends to be a bit of a stepchild) but it is possible to run `nim` on windows and some people might want to develop `nim` code changes on windows. Yes, I didn't think of this before and not a reason not to forge ahead.

It appears bats works on Window as per the installation instructions here: https://bats-core.readthedocs.io/en/latest/installation.html#installing-bats-from-source-onto-windows-git-bash

Windows does not have native bash support now using WSL so don't see any reason why this wouldn't the same as OS X or Linux: https://hackernoon.com/how-to-install-bash-on-windows-10-lqb73yj3

**Comment by jthomas** [comment]
We've now moved to using NPM to run the tests and manage bats dependencies - this makes it cross-platform as we're not using brew anymore.
